### ISSUE TITLE
queation about this paper

### ISSUE THREAD

**Issue by taylorgag** [MRdoulestar/DeeSCVHunter#1]
您好，看您居住地是中国，我就直接用汉语了。现在这篇文章是直接接收了吗？想问一些问题，关于深度学习检测智能合约漏洞方面的。您看方面吗

**Comment by MRdoulestar** [comment]
> 您好，看您居住地是中国，我就直接用汉语了。现在这篇文章是直接接收了吗？想问一些问题，关于深度学习检测智能合约漏洞方面的。您看方面吗

您好，方便的，paper中也是引用了你们的工作

**Comment by taylorgag** [comment]
可以加一下联系方式吗，或者不方便的话，现在文章可以看一下嘛



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 14, 2021 22:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MRdoulestar/DeeSCVHunter] queation about this paper (#1)




  
您好，看您居住地是中国，我就直接用汉语了。现在这篇文章是直接接收了吗？想问一些问题，关于深度学习检测智能合约漏洞方面的。您看方面吗
  
您好，方便的，paper中也是引用了你们的工作

**Comment by MRdoulestar** [comment]
> 可以加一下联系方式吗，或者不方便的话，现在文章可以看一下嘛
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Apr 14, 2021 22:09 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [MRdoulestar/DeeSCVHunter] queation about this paper (#1) 您好，看您居住地是中国，我就直接用汉语了。现在这篇文章是直接接收了吗？想问一些问题，关于深度学习检测智能合约漏洞方面的。您看方面吗 您好，方便的，paper中也是引用了你们的工作 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您可以留个邮箱地址，我把联系方式给您发过去

**Comment by taylorgag** [comment]
我的qq：2737237681
麻烦您加一下我把，谢谢



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 14, 2021 22:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MRdoulestar/DeeSCVHunter] queation about this paper (#1)




  
可以加一下联系方式吗，或者不方便的话，现在文章可以看一下嘛
 …
 ---Original--- From: @.&gt; Date: Wed, Apr 14, 2021 22:09 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [MRdoulestar/DeeSCVHunter] queation about this paper (#1) 您好，看您居住地是中国，我就直接用汉语了。现在这篇文章是直接接收了吗？想问一些问题，关于深度学习检测智能合约漏洞方面的。您看方面吗 您好，方便的，paper中也是引用了你们的工作 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您可以留个邮箱地址，我把联系方式给您发过去
